apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  annotations:
spec:
  ports:
  - port: 80 
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: heartbeat
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: heartbeat-deployment
spec:
  selector:
    matchLabels:
      app: heartbeat
  replicas: 1
  template:
    metadata:
      labels:
        app: heartbeat
    spec:
      containers:
      - name: heartbeatcontainer
        image: jakkaj/monheartbeat:latest # Update the version of nginx from 1.7.9 to 1.8
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux

