apiVersion: v1
kind: Service
metadata:
  name: heartmonitor
  annotations:
    #service.beta.kubernetes.io/azure-load-balancer-internal: "true"
   # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "default"
spec:
  #loadBalancerIP: 192.168.210.46
  ports:
  - port: 80 
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: heartmonitor
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: heartmonitor-deployment
spec:
  selector:
    matchLabels:
      app: heartmonitor
  replicas: 1
  template:
    metadata:
      labels:
        app: heartmonitor
    spec:
      containers:
      - name: heartmonitorcontainer
        image: jakkaj/monheartmonitor:latest # Update the version of nginx from 1.7.9 to 1.8
        ports:
        - containerPort: 80      
      nodeSelector:
        beta.kubernetes.io/os: linux

