apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-svc1-{{.Values.Version}}-{{.Values.Build}}
spec:
  hosts:
  - svc1-{{.Values.Version}}-{{.Values.Build}}
  http:
  - route:
    - destination:
        host: svc1-{{.Values.Version}}-{{.Values.Build}}
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-svc2-{{.Values.Version}}-{{.Values.Build}}
spec:
  hosts:
  - svc2-{{.Values.Version}}-{{.Values.Build}}
  http:
  - route:
    - destination:
        host: svc2-{{.Values.Version}}-{{.Values.Build}}
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-svc3-{{.Values.Version}}-{{.Values.Build}}
spec:
  hosts:
  - svc3-{{.Values.Version}}-{{.Values.Build}}
  http:
  - route:
    - destination:
        host: svc3-{{.Values.Version}}-{{.Values.Build}}
        subset: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: svc3-dr-{{.Values.Version}}-{{.Values.Build}}
spec:
  host: svc3-{{.Values.Version}}-{{.Values.Build}}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: svc2-dr-{{.Values.Version}}-{{.Values.Build}}
spec:
  host: svc2-{{.Values.Version}}-{{.Values.Build}}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: svc1-dr-{{.Values.Version}}-{{.Values.Build}}
spec:
  host: svc1-{{.Values.Version}}-{{.Values.Build}}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3



