{{- $root := . -}}
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets-{{.Values.Version}}-{{.Values.Build}}
  namespace: default
data:
  eventhub_read_policy_key: {{.Values.eventhub_read_policy_key | quote}}
  eventhub_read_policy_name: {{.Values.eventhub_read_policy_name | quote}}
  eventhub_name: {{.Values.eventhub_name | quote}}
  eventhub_namespace: {{.Values.eventhub_namespace | quote}}
  cosmos_service_endpoint: {{.Values.cosmos_service_endpoint | quote}}
  cosmos_key: {{.Values.cosmos_key | quote}}
  cosmos_database_name: {{.Values.cosmos_database_name | quote}}
  cosmos_collection_name: {{.Values.cosmos_collection_name | quote}}