apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datagen-slow
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datagen-slow
    spec:
      containers:
      - name: datagen-slow
        image: jakkaj/datagen:slow
      imagePullSecrets:
      - name: acr-auth-ravenswoodregistry