apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "svc2-v2-{{.Values.Version}}-{{.Values.Build}}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"   
    app: "svc2-v2-{{.Values.Version}}-{{.Values.Build}}"
spec: 
  selector:
    matchLabels:
      app: "svc2-{{.Values.Version}}-{{.Values.Build}}"
      version: v2
  replicas: {{.Values.Servers}}
  template:
    metadata:
      labels:
        app: "svc2-{{.Values.Version}}-{{.Values.Build}}"
        version: v2
    spec:
      containers:
      - name: svc
        imagePullPolicy: {{.Values.ImagePullPolicy}}
        image: {{.Values.ImageOther}}
        resources:
          requests:
            memory: {{.Values.Memory}}
            cpu: {{.Values.Cpu}}
        ports:
        - containerPort: 80
          name: http      
        env:
        - name: WRITE_BACK
          value: svc2v2     
        - name: WRITE_FIELD
          value: svc2
        - name: CLUSTER
          valueFrom:
            configMapKeyRef:                 
              name: ravenswoodconfig                 
              key: this_cluster    