apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: (base64 encoded string containing the storage account name e.g. somestorage | base64)
  azurestorageaccountkey: (base64 encoded string containing the storage account key e.g. a bunch of bas64 encoded gabage looking string)