apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  # The label is used for matching the exact claim
  labels:
    usage: pv0001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:    
    secretName: azure-secret
    # Replace with correct storage share name
    shareName: heartmon
    # In case the secret is stored in a different namespace
    #shareNamespace: default
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azurefilecustom
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: pv0001